# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.2 on Sat May 26 19:11:57 2018
#

import wx
# begin wxGlade: dependencies
import wx.adv
import wx.propgrid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LayerConfDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LayerConfDlg.__init__
        kwds["style"] = kwds.get("style", 0) | wx.FULL_REPAINT_ON_RESIZE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((415, 541))
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Layer property"))
        self.hyperlink_1 = wx.adv.HyperlinkCtrl(self, wx.ID_ANY, _("hyperlink_1"), _("https://en.wikipedia.org/wiki/ZbV"), style=wx.adv.HL_ALIGN_CENTRE)
        self.property_grid_1 = wx.propgrid.PropertyGridManager(self, wx.ID_ANY, style=wx.propgrid.PG_BOLD_MODIFIED | wx.propgrid.PG_DESCRIPTION | wx.propgrid.PG_HIDE_CATEGORIES | wx.propgrid.PG_HIDE_MARGIN)
        self.hyperlink_2 = wx.adv.HyperlinkCtrl(self, wx.ID_ANY, _("Help"), _("https://www.google.com/"))
        self.button_Cancel = wx.Button(self, wx.ID_CANCEL, "")
        self.button_OK = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.propgrid.EVT_PG_SELECTED, self.OnPropertySelectionCanged, self.property_grid_1)
        self.Bind(wx.adv.EVT_HYPERLINK, self.OnPropertyHelpHyperlink, self.hyperlink_2)
        self.Bind(wx.EVT_BUTTON, self.OnButtonCancel, self.button_Cancel)
        self.Bind(wx.EVT_BUTTON, self.OnButtonOK, self.button_OK)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LayerConfDlg.__set_properties
        self.SetTitle(_("Layer Configuration"))
        self.SetSize((415, 541))
        self.label_1.SetFont(wx.Font(16, wx.DECORATIVE, wx.NORMAL, wx.BOLD, 0, ""))
        self.hyperlink_1.SetToolTip(_("Tap to open help in system browser"))
        self.hyperlink_2.SetToolTip(_("Search for help on selected property"))
        self.button_Cancel.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LayerConfDlg.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.hyperlink_1, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_2.Add(self.property_grid_1, 5, wx.ALL | wx.EXPAND, 10)
        sizer_3.Add(self.hyperlink_2, 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
        sizer_3.Add((1, 1), 2, wx.EXPAND, 0)
        sizer_3.Add(self.button_Cancel, 0, wx.ALIGN_CENTER | wx.ALL, 7)
        sizer_3.Add(self.button_OK, 0, wx.ALIGN_CENTER | wx.ALL, 7)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((0, 0), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnPropertySelectionCanged(self, event):  # wxGlade: LayerConfDlg.<event_handler>
        print("Event handler 'OnPropertySelectionCanged' not implemented!")
        event.Skip()

    def OnPropertyHelpHyperlink(self, event):  # wxGlade: LayerConfDlg.<event_handler>
        print("Event handler 'OnPropertyHelpHyperlink' not implemented!")
        event.Skip()

    def OnButtonCancel(self, event):  # wxGlade: LayerConfDlg.<event_handler>
        print("Event handler 'OnButtonCancel' not implemented!")
        event.Skip()

    def OnButtonOK(self, event):  # wxGlade: LayerConfDlg.<event_handler>
        print("Event handler 'OnButtonOK' not implemented!")
        event.Skip()

# end of class LayerConfDlg
