# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.2 on Sat May 26 19:11:57 2018
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialogAbout(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialogAbout.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialogAbout.__set_properties
        self.SetTitle(_("About"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialogAbout.__do_layout
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/damir/PycharmProjects/zbv/src/wxgui/glade_gui/sinus.jpeg", wx.BITMAP_TYPE_ANY))
        sizer_9.Add(bitmap_1, 0, 0, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, _("zbv \nv0"), style=wx.ALIGN_RIGHT)
        label_2.SetFont(wx.Font(40, wx.SCRIPT, wx.NORMAL, wx.BOLD, 0, ""))
        sizer_9.Add(label_2, 0, wx.ALIGN_RIGHT | wx.ALL, 7)
        sizer_9.Add((0, 0), 0, 0, 0)
        sizer_8.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_8.Add(self.panel_1, 4, wx.EXPAND, 0)
        sizer_8.Add((0, 0), 0, 0, 0)
        self.SetSizer(sizer_8)
        sizer_8.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyDialogAbout
